[project]
name = "bigearthnet-dl-distributed"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.23",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "nbconvert>=7.16.6",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "rasterio>=1.5.0",
]
